[project]
name = "string-utils"
version = "1.0.0"
description = "String utility functions for Strata"
author = "Strata Contributors"
license = "GPL-3.0"
repository = "https://github.com/strata-lang/string-utils"
homepage = "https://github.com/strata-lang/string-utils"
strata = ">=1.0.0"

[exports]
string = "./src/string.str"

[dependencies]
